# GitHub Secret Scanning Configuration
# This file excludes specific paths from secret scanning

paths-ignore:
  - 'src/services/geminiAccountService.js'
  - 'data/demo/Gemini-CLI-2-API/gemini-core.js'