name = "crs-pages"
compatibility_date = "2024-01-01"

[env.production]
name = "crs-pages"

[env.development]
name = "crs-pages-dev"

# Pages配置通过wrangler pages命令管理
# 这个文件主要用于Functions配置（如果需要）

# 如果需要Pages Functions，可以在这里配置
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-id"